channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal
  - python
  - numpy
  - scikit-learn
  - samtools
  - minimap2
  - mummer4
  - nanosim
  - htseq
  - bedtools
  - r-base
  - r-stringdist
  - r-caret
  - r-e1071
  - r-markdown
  - anaconda::tbb=2020.3
  - anaconda::tbb-devel=2020.3
