---
title: "ScNapBar results"
output: pdf_document
fontsize: 12pt
---
```{r global_options, include=FALSE}
Sys.setlocale("LC_NUMERIC","C")
options(stringsAsFactors = FALSE)
args = commandArgs(trailingOnly=TRUE)
library(reshape2)
library(ggplot2)
names(args)=c('sim_barcodes','sim_label','sim_prob','real_pred','cutoff','sis_pred')
args = as.list(args)
args$cutoff=as.integer(args$cutoff)
feat = c("adaptor_score", "barcode_score", "barcode_indel", "barcode_start", "barcode_mismatch", "umi_length", "polyT_length")
nfeat=length(feat)
```

# Simulated reads
## Benchmarking
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=4}
v = seq(0,100)
t1=read.table(args$sim_barcodes)
m =read.table(args$sim_label, header=TRUE)
df=do.call(rbind,lapply(v,function(d) {
t2=m[m[,3]>d,1:2]
i=match(t1[,1], t2[,1])
pred=as.integer(is.na(t2[i,2]))
fal=t2[i,2]!=t1[,3]
fal[is.na(fal)]=FALSE
unal=grepl('_unal',t1[,1])
gtruth=as.integer(unal | fal)
res=caret::confusionMatrix(factor(pred), factor(gtruth))
c(res$overall,res$byClass)[c(1,8,9,12,14)]
}))
rownames(df)=v
df=df[!is.na(df[,4]),]
df=melt(df)
colnames(df)[2]='Measures'
ggplot(df,aes(Var1,value,col=Measures))+geom_line()+geom_vline(xintercept=args$cutoff, linetype=4)+
labs(x='Predicted probability cutoff',y='Scores')
```

## Feature distributions
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
x=read.table(args$sim_prob,header=TRUE)
df=data.frame(assignment=rep(c('wrong','correct')[as.integer(x$pred>args$cutoff)+1],nfeat),melt(x[,feat],id.vars=NULL))
ggplot(df,aes(value,fill=assignment))+geom_histogram()+facet_wrap(~variable,scale="free")
```

## Assignment score distributions
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
df=read.table(args$sim_prob,header=TRUE)
df$Assignment=c('correct','wrong')[df$label+1]
ggplot(df, aes(x = pred, group = Assignment)) + geom_density(aes(color = Assignment))+ labs(x='Scores', y='Density')
```

# Nanopore reads
## Feature distributions
```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, cache.lazy=FALSE, fig.width=8, fig.height=6}
x=read.table(args$real_pred,header=TRUE)
df=data.frame(assignment=rep(c('unassigned','assigned')[as.integer(x$pred>args$cutoff)+1],nfeat),melt(x[,feat],id.vars=NULL))
ggplot(df,aes(value,fill=assignment))+geom_histogram()+facet_wrap(~variable,scale="free")
```

```{r, eval=FALSE, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, cache.lazy=FALSE, fig.width=8, fig.height=6}
x=read.table(args$sis_pred,header=TRUE)
df=data.frame(assignment=c('Not found by Sicelore','Same with Sicelore','Diff. with Sicelore')[x$X.1+2],melt(x[,feat],id.vars=NULL))
ggplot(df,aes(value,fill=assignment))+geom_histogram()+facet_wrap(~variable,scale="free")+ labs(x='Feature distributions compared with Sicelore')
```
