library(stringdist)
options(stringsAsFactors = FALSE)
Sys.setlocale("LC_NUMERIC","C")
args = commandArgs(trailingOnly=TRUE)
x=read.table(args[1])
y=read.table(args[2])
r=unlist(lapply(y[seq(2,nrow(y),2),1],function(d) x[stringdist(d,x[,2],method='dl')<2,2]))
write.table(r,file=args[3],sep="\t",quote=F,row.names=F,col.names=F)
